### ISSUE TITLE
Allow manual deployment

### ISSUE THREAD

**Issue by sista05** [dagster-io/dagster-cloud-action#133]
I am thinking of an environment where MFA must be entered in AWS, or where I may want to arbitrarily enter a value into a variable for testing purposes.

The current process of hybrid_branch_deploy is as follows, but if github actions by workflow_dispatch without a pull request, github.event.number will be empty and the deploy will Deploy will always fail.

```
    - name: Deploy to Dagster Cloud
      uses: ./action-repo/actions/utils/deploy
      id: deploy
      with:
        organization_id: ${{ inputs.organization_id }}
        pr: "${{ github.event.number }}"
        pr_status: "${{ github.event.pull_request.merged && 'merged' || github.event.pull_request.state }}"
        location: ${{ inputs.location }}
        image_tag: ${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}
      env:
        DAGSTER_CLOUD_API_TOKEN: ${{ inputs.dagster_cloud_api_token }}
```
