### ISSUE TITLE
Python 3.8 removed from latest ubuntu runners

### ISSUE THREAD

**Issue by mjclarke94** [dagster-io/dagster-cloud-action#163]
Python 3.8 is not present on the latest runner images for ubuntu, as it is no longer actively maintained. Not only does this result in a need to pin to older runner images, but means the deployment workflow relies on a version of python which doesn't receive security updates anymore.

Unpinning to just use whatever python version is present on the runner image might be the cleanest solution here.

**Comment by benpankow** [comment]
Thanks for the report, Matt - I believe to address this we'll need to publish a new `dagster-cloud.pex` on a more recent Python version - right now we only have published one for 3.8.

**Comment by ezpzbz** [comment]
@benpankow is there any tentative timeline when this is gonna happen? We still need to use `ubuntu-20.04`.
I just tried with action `v0.1.43` and failed with the same reason
`/usr/bin/env: ‘python3.8’: No such file or directory`

**Comment by joscha** [comment]
This started appearing about 2h ago with Ubuntu 22.04 runners for me:

In the `Validate configuration` step:

```
Run dagster-io/dagster-cloud-action/actions/utils/dagster-cloud-cli@v0.1
  with:
    command: ci check --project-dir . --dagster-cloud-yaml-path dagster_cloud.yaml
  env:
    DAGSTER_CLOUD_API_TOKEN: ***
    ENABLE_FAST_DEPLOYS: true
    PYTHON_VERSION: 3.1.2
    DAGSTER_CLOUD_YAML_PATH: .
    DAGSTER_CLOUD_FILE: dagster_cloud.yaml
    DAGSTER_CLOUD_ORGANIZATION: my-org
    GITHUB_TOKEN: ***
Run $GITHUB_ACTION_PATH/../../../generated/gha/dagster-cloud.pex -m dagster_cloud_cli.entrypoint ci check --project-dir . --dagster-cloud-yaml-path dagster_cloud.yaml
  $GITHUB_ACTION_PATH/../../../generated/gha/dagster-cloud.pex -m dagster_cloud_cli.entrypoint ci check --project-dir . --dagster-cloud-yaml-path dagster_cloud.yaml
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    DAGSTER_CLOUD_API_TOKEN: ***
    ENABLE_FAST_DEPLOYS: true
    PYTHON_VERSION: 3.12
    DAGSTER_CLOUD_YAML_PATH: .
    DAGSTER_CLOUD_FILE: dagster_cloud.yaml
    DAGSTER_CLOUD_ORGANIZATION: my-org
    GITHUB_TOKEN: ***
/usr/bin/env: ‘python3.8’: No such file or directory
```
