### ISSUE TITLE
The `utils/run` action does not expose API Token argument

### ISSUE THREAD

**Issue by stkbailey** [dagster-io/dagster-cloud-action#54]
Description: I would like to be able to launch a job from a Github Action context when our build / update pipeline completess. There is a `run` action provided that seems to do what I need, but I am unable to get it to work.

Here is some example code:

```
      - name: Run Job
        uses: dagster-io/dagster-cloud-action/actions/utils/run@v0.1
        with:
          dagster_cloud_url: https://my_space.dagster.cloud
          deployment: my_deployment
          location_name: my_location
          repository: my_repo
          job: my_job
        env:
          DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
```

Providing the `DAGSTER_CLOUD_API_TOKEN` may allow me to run this code, but I am also getting an unrelated error related to `INPUT_REGISTRY_ENV`: 

```
/usr/bin/docker run --name ghcriodagsteriodagstercloudaction018_1603de --label 8d5581 --workdir /github/workspace --rm -e "AWS_IAM_ROLE" -e "DAGSTER_CODE_LOCATION_FILE" -e "DOCKER_BUILD_FOLDER" -e "DOCKER_REGISTRY" -e "LATEST_TAG" -e "AWS_DEFAULT_REGION" -e "AWS_REGION" -e "AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY" -e "AWS_SESSION_TOKEN" -e "SSH_AUTH_SOCK" -e "SSH_AGENT_PID" -e "DAGSTER_CLOUD_API_TOKEN" -e "INPUT_DAGSTER_CLOUD_URL" -e "INPUT_DEPLOYMENT" -e "INPUT_LOCATION_NAME" -e "INPUT_REPOSITORY" -e "INPUT_JOB" -e "INPUT_ORGANIZATION_ID" -e "INPUT_LOCATION" -e "INPUT_TAGS_JSON" -e "INPUT_CONFIG_JSON" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e GITHUB_ACTIONS=true -e CI=true --entrypoint "/run.sh" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/my-repo/my-repo":"/github/workspace" ghcr.io/dagster-io/dagster-cloud-action:0.1.8  ""
/run.sh: line 17: INPUT_REGISTRY_ENV: invalid indirect expansion
```

Solution:

I think this action ought to be cleaned up and an example GH Actions template provided for end users.

It would also be great if this action (or a separate one) could poll the run until it is complete.

References:
- Script: https://github.com/dagster-io/dagster-cloud-action/blob/main/src/run.sh
- Action: https://github.com/dagster-io/dagster-cloud-action/blob/main/actions/utils/run/action.yml
