### ISSUE TITLE
Allow `ssh` authentication during Docker build step

### ISSUE THREAD

**Issue by stkbailey** [dagster-io/dagster-cloud-action#86]
If users are accessing private Python packages in their Docker images, they need to provide a means to authenticate against Github (or other sources) from within the Docker context. One way to do this using Docker Buildx action is to pass in the `ssh` argument to the build context. This is how we at Whatnot are currently running the action, which we push to an ECR repository, then run the `update-only` action to update Dagster Cloud. However, we would prefer to use the comprehensive deploy actions provided here.

I think this is a simple change. For example, in [the prod_deploy action](https://github.com/dagster-io/dagster-cloud-action/blob/07f8cf196a322af4048eee2af70fd19a83fb841e/actions/hybrid_prod_deploy/action.yml#L58)
```
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
-->     ssh: default
        context: ${{ fromJson(inputs.location).directory }}
        push: true
        tags: "${{ fromJson(inputs.location).registry }}:${{ github.sha }}"
        labels: |
          branch=${{ github.head_ref }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
```

I _think_ If this argument were passed in the action, then users could set up their SSH keys before calling the Dagster Cloud action, and then the pre-built action could access the private repository.

```
     # set up SSH key before calling Dagster cloud Deploy action
     - name: Set up default SSH Key for Github
        uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.MY_SSH_PRIV_KEY }}

      # deploy dagster cloud
      - name: Build and deploy to Dagster Cloud hybrid
        uses: dagster-io/dagster-cloud-action/actions/hybrid_prod_deploy@v0.1
        with:
          dagster_cloud_api_token: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
          location: ${{ toJson(matrix.location) }}
          organization_id: ${{ env.ORGANIZATION_ID }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Happy to contribute this if there's no issues. Even if it's not configurable within the action, I think it would at least provide a means for accomplishing the objective.

**Comment by shalabhc** [comment]
Hi Stephen, how do you reference the private repos in your build code? Is it a line in `requirements.txt` or some custom command you run to clone it locally into the docker image?

If you want to test your suggestion, I've made your change in the `test-docker-ssh` branch: https://github.com/dagster-io/dagster-cloud-action/blob/70b5bb77387edc55dc10950250161c4e23bbbb48/actions/hybrid_prod_deploy/action.yml#L52

You can try appending `@test-docker-ssh` to the [reference](https://github.com/dagster-io/dagster-cloud-action/blob/main/.github/workflows/hybrid_deploy.yml#L48) to this action in your deploy.yml to see if this works.

Another option for private repos might be to first clone the repo locally using `actions/checkout` and adding a relative path like `../../path/to/private/repo` to your `requirements.txt`.

**Comment by stkbailey** [comment]
@shalabhc , we have them specified in a `pyproject.toml` file, which we then install in our Dockerfile

```
[tool.poetry.dependencies]
python = "^3.8,<3.11"
dagit = "^1.1.11"
...
private-repo= {git = "git+ssh://git@github.com/Whatnot-Inc/my-private-repo.git", tag = "v0.1.5"}
```

then we install poetry, and poetry install.

```

# Project initialization
COPY pyproject.toml poetry.lock ./

# Install poetry to ensure Python dependencies are correct
RUN pip install poetry==1.2.1
RUN --mount=type=ssh \
    poetry config virtualenvs.create false \
    && poetry install --only main
```

I'll give this a shot with the test action. Thanks!

**Comment by stkbailey** [comment]
@shalabhc I can confirm that adding the argument to the build step allowed me to successfully build/push -- action looks as follows.

```
  steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_IAM_ROLE }}
          aws-region:  ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up default SSH Key for Github
        uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.MY_SSH_PRIV_KEY }}

      - name: Build and deploy to "stage" deployment to Dagster Cloud
        uses: dagster-io/dagster-cloud-action/actions/hybrid_prod_deploy@test-docker-ssh
        with:
          dagster_cloud_api_token: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
          location: ${{ toJson(matrix.location) }}
          organization_id: ${{ env.ORGANIZATION_ID }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
