### ISSUE TITLE
Notify step in `hybrid_branch_deploy` action not specifying branch URL

### ISSUE THREAD

**Issue by stkbailey** [dagster-io/dagster-cloud-action#97]
We have noticed that our Notify step in branch deployments has not been correctly injecting the branch deployment ID into the URL recently. So, instead of `https://my_org.dagster.cloud/<branch_id>/home`, it redirects to `https://my_org.dagster.cloud//home`.

I'm not aware of any recent changes to our workflow strategy here.

![image](https://user-images.githubusercontent.com/7850417/219383448-4e4ea3b9-522c-4953-bd1f-d9e858328c82.png)

Below is our code block that we are using currently.

```
      - name: Build and deploy branch deployment to Dagster Cloud
        uses: dagster-io/dagster-cloud-action/actions/hybrid_branch_deploy@v0.1
        with:
          dagster_cloud_api_token: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
          location: ${{ toJson(matrix.location) }}
          organization_id: ${{ env.ORGANIZATION_ID }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
